### ISSUE TITLE
permission was denied

### ISSUE THREAD

**Issue by jinlingwanggit** [ElofssonLab/TOPCONS2#2]
Hi,

I used  pfam_workflow_octopus.py with docker in the past. It was woking fine.  But recently it gave me the error "OSError: [Errno 13] Permission denied: '/scratch/seq_0_IC_akT' .  The test run " ../run_topcons2.sh one_seq.fasta -outpath rst1" seems ok. 

Any suggestions on how to fixing this permission issue?

Thank you

Jin

**Comment by arneelof** [comment]
We will investigate...


Yours

Arne

-----------------------------------------
  Arne Elofsson                  Science for Life Laboratory
  Tel:+46-(0)70 695 1045   Stockholm University
  http://bioinfo.se/               Box 1031,
  Email: arne@bioinfo.se   17121 Solna, Sweden
  Twitter:   https://twitter.com/arneelof
  Scholar: http://scholar.google.se/citations?user=s3OCM3AAAAAJ
  ORCID: 0000-0002-7115-9751

**Comment by nanjiangshu** [comment]
Hi @jinlingwanggit, thanks for pointing out the problem. It is caused by a recent update of the main workflow. The problem is solved now. Please wait for a couple of hours to let the Docker image building complete and then make a new docker pull by 

```
docker pull nanjiang/topcons2
```
Then follow the updated instructions at 
https://github.com/ElofssonLab/TOPCONS2#run-only-the-sub-predictors-octopus-and-spoctopus-using-docker

I have added a new script `run_octopus.sh` to make the command line simpler. 

Best,

Nanjiang

**Comment by arneelof** [comment]
Tack

On 16 Feb 2018 17:26, "Nanjiang Shu" <notifications@github.com> wrote:

Hi @jinlingwanggit <https://github.com/jinlingwanggit>, thanks for pointing
out the problem. It is caused by a recent update of the main workflow. The
problem is solved now. Please wait for a couple of hours to let the Docker
image building complete and then make a new docker pull by

docker pull nanjiang/topcons2

Then follow the updated instructions at
https://github.com/ElofssonLab/TOPCONS2#run-only-the-sub-predictors-octopus-
and-spoctopus-using-docker

I have added a new script run_octopus.sh to make the command line simpler.

Best,

Nanjiang

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ElofssonLab/TOPCONS2/issues/2#issuecomment-366284175>,
or mute the thread
