### ISSUE TITLE
Hardware Specifications

### ISSUE THREAD

**Issue by yoreai** [ElofssonLab/TOPCONS2#3]
I hope it is to ask questions here:

Problem: 
- I am trying to get topology information on about 100,000 sequences. I didn't want to lock out your server and pulled the docker container you've provided here.
- To process about 100 sequences per minute, what hardware specs would you recommend for the server? I am running the docker instance locally, and it took me about 4 hours for 20 sequences. I would like to scale up (probably on EC2).

**Comment by arneelof** [comment]
Thanks for using topcons. Look at the statistics page for the relevant
numbers.

100k sequences is not a problem if the server, we can often handle that in
a day. Use the api for easy submission

The average runtime should be about 60 seconds (on an single core machine i
think). Så there is something strange with the docker version. Nanjiang do
you have any idea?

**Comment by nanjiangshu** [comment]
Hi, 

If there are Pfam hits found for the query sequence, it usually takes just a few seconds to make a prediction for TOPCONS. However, if no Pfam hits are found, the running time will be significantly longer since a full `blastpgp` run against the `uniref90` database will be run to generate the sequence profile. The average running time per sequence is about 2 minutes according to our web-server (`blastpgp` is actually using at the maximum 4 cores). In your case, I would guess either all (or most) of these 20 sequences do not find any Pfam hits and thus a full `blastpgp` searching is run. If this is not the true, it could also because your PfamA database is not correctly installed. 

In general, I would say the TOPCONS web-server can handle a job with 100,000 sequences and it should be finished within one month. The job may finish faster if a significant amount of sequences have cached results on the web-server. 

So if you are not in a hurry, I would suggest you to submit the sequences to our web-server unless you want to have strict control of the Pfam database and sequence database for PSIBLAST. 

The topcons.net web-server is down at the moment I'm writing this letter (and it seems all servers are down at our institute). So please be patient until the server is back online.

Best,

Nanjiang

**Comment by yoreai** [comment]
@arneelof and @nanjiangshu - Thank you very much for your prompt responses! It sounds like I should use your api. 
Last question: is it better to submit sequences in batches of 1000 (for example), or just one single big job?

**Comment by nanjiangshu** [comment]
Better in smaller parts as you suggested. 

Best,

Nanjiang

**Comment by yoreai** [comment]
Thank you!!!
